name: my first workflow run

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: welcome message
          run: echo "my first github actions job"

        - name: List files
          run: ls

        - name: read file
          run: cat test.py



